stages:
  - deploy

variables:
  - WEBMENTION_IO_TOKEN: $WEBMENTION_IO_TOKEN

netlify:
  stage: deploy
  image: node:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: production
    url: https://brycewray.com
  only:
    - schedules
  script:
    - "rm -rf _site"
    - npm install
    - npm i -g netlify-cli
    - npm run build
    - netlify deploy -s $NETLIFY_SITE_ID -p _site -t $NETLIFY_AUTH_TOKEN -e production
  artifacts:
    paths:
      - public