stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://brycewray.com
  only:
    - master
  script:
    - "rm -rf _site"
    - npm install
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID -p _site $NETLIFY_AUTH_TOKEN
  artifacts:
    paths:
      - public
  only:
    - master