stages:
  - deploy

image: node:latest

variables:
  WEBMENTION_IO_TOKEN: $WEBMENTION_IO_TOKEN
  
netlify:
  stage: deploy
  rules:
    # - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  environment:
    name: production
    url: https://brycewray.com
  script:
    - "rm -rf _site"
    - npm install
    - npm i -g netlify-cli
    - npm run build
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
#  artifacts:
#    paths:
#      - public