stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: production
    url: https://brycewray.com
  only:
    - schedules
  script:
    - "rm -rf _site"
    - npm install
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID -p _site $NETLIFY_AUTH_TOKEN
  artifacts:
    paths:
      - public