name: Deploy to Vercel

# To do a push without triggering this GHA, include one of
# the following in the **commit message**
# (INCLUDING the brackets AND case-sensitivity):
#
# [skip ci]
# [ci skip]
# [no ci]
# [skip actions]
# [actions skip]
#
# “Alternatively, you can end the commit message
# with two empty lines followed by either
# `skip-checks: true` or `skip-checks:true`.”
#
# ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # every day at 12:00 UTC (0700CDT/0600CST)
    # The above is to make sure static tweets' images don't run afoul
    # of Twitter's caching strategy
  #   - cron: '0 0 * * *'   # every day at 00:00UTC (1900CDT/1800CST)
  #   - cron: '0 8 * * *'   # every day at 08:00UTC (0300CDT/0200CST)
  #   - cron: '0 16 * * *'  # every day at 16:00UTC (1100CDT/1000CST)
  # workflow_dispatch:
  # above line is for if GHA fails, but we don't have this in this GHA yet - 2022-09-21

env:
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
  TOKEN: ${{ secrets.TOKEN }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  # WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Fetch **all** history (not just deploy commit) for `gitinfo.js`
          # See https://discourse.gohugo.io/t/problems-with-gitinfo-in-ci/22480
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install packages
        run: npm install
      - name: Build site
        run: npm run build
      - name: Run Pagefind
        run: npm_config_yes=true npx pagefind --source "_site"
      - name: Publish to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_STATIC_SITE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          WORKING_DIRECTORY: '_site'
          # BUILD_ENV: |
          #   WEBMENTION_IO_TOKEN="${{ secrets.WEBMENTION_IO_TOKEN }}"
          # ALIAS_DOMAINS: |
          #   brycewray.com
          #   www.brycewray.com
